/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pl.grzeslowski.jsupla.api.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ChannelFunctionActionEnum
 */
@JsonAdapter(ChannelFunctionActionEnum.Adapter.class)
public enum ChannelFunctionActionEnum {
  
  OPEN("OPEN"),
  
  CLOSE("CLOSE"),
  
  SHUT("SHUT"),
  
  REVEAL("REVEAL"),
  
  REVEAL_PARTIALLY("REVEAL_PARTIALLY"),
  
  TURN_ON("TURN_ON"),
  
  TURN_OFF("TURN_OFF"),
  
  SET_RGBW_PARAMETERS("SET_RGBW_PARAMETERS"),
  
  OPEN_CLOSE("OPEN_CLOSE"),
  
  STOP("STOP");

  private String value;

  ChannelFunctionActionEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ChannelFunctionActionEnum fromValue(String text) {
    for (ChannelFunctionActionEnum b : ChannelFunctionActionEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ChannelFunctionActionEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final ChannelFunctionActionEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ChannelFunctionActionEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ChannelFunctionActionEnum.fromValue(String.valueOf(value));
    }
  }
}

