/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AccessIdentifierUpdateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-03T19:40:18.502Z")
public class AccessIdentifierUpdateRequest {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("caption")
  private String caption = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("locationsIds")
  private List<Integer> locationsIds = null;

  @SerializedName("clientAppsIds")
  private List<Integer> clientAppsIds = null;

  public AccessIdentifierUpdateRequest enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public AccessIdentifierUpdateRequest caption(String caption) {
    this.caption = caption;
    return this;
  }

   /**
   * Get caption
   * @return caption
  **/
  @ApiModelProperty(value = "")
  public String getCaption() {
    return caption;
  }

  public void setCaption(String caption) {
    this.caption = caption;
  }

  public AccessIdentifierUpdateRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Provide new password if you want to change it.
   * @return password
  **/
  @ApiModelProperty(value = "Provide new password if you want to change it.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public AccessIdentifierUpdateRequest locationsIds(List<Integer> locationsIds) {
    this.locationsIds = locationsIds;
    return this;
  }

  public AccessIdentifierUpdateRequest addLocationsIdsItem(Integer locationsIdsItem) {
    if (this.locationsIds == null) {
      this.locationsIds = new ArrayList<Integer>();
    }
    this.locationsIds.add(locationsIdsItem);
    return this;
  }

   /**
   * Locations identifiers to assign to this Access Identifier.
   * @return locationsIds
  **/
  @ApiModelProperty(value = "Locations identifiers to assign to this Access Identifier.")
  public List<Integer> getLocationsIds() {
    return locationsIds;
  }

  public void setLocationsIds(List<Integer> locationsIds) {
    this.locationsIds = locationsIds;
  }

  public AccessIdentifierUpdateRequest clientAppsIds(List<Integer> clientAppsIds) {
    this.clientAppsIds = clientAppsIds;
    return this;
  }

  public AccessIdentifierUpdateRequest addClientAppsIdsItem(Integer clientAppsIdsItem) {
    if (this.clientAppsIds == null) {
      this.clientAppsIds = new ArrayList<Integer>();
    }
    this.clientAppsIds.add(clientAppsIdsItem);
    return this;
  }

   /**
   * Client Apps identifiers to assign to this Access Identifier. If client app is connected to any other Client ID, it will be disconnected from the old one before assigning.
   * @return clientAppsIds
  **/
  @ApiModelProperty(value = "Client Apps identifiers to assign to this Access Identifier. If client app is connected to any other Client ID, it will be disconnected from the old one before assigning.")
  public List<Integer> getClientAppsIds() {
    return clientAppsIds;
  }

  public void setClientAppsIds(List<Integer> clientAppsIds) {
    this.clientAppsIds = clientAppsIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessIdentifierUpdateRequest accessIdentifierUpdateRequest = (AccessIdentifierUpdateRequest) o;
    return Objects.equals(this.enabled, accessIdentifierUpdateRequest.enabled) &&
        Objects.equals(this.caption, accessIdentifierUpdateRequest.caption) &&
        Objects.equals(this.password, accessIdentifierUpdateRequest.password) &&
        Objects.equals(this.locationsIds, accessIdentifierUpdateRequest.locationsIds) &&
        Objects.equals(this.clientAppsIds, accessIdentifierUpdateRequest.clientAppsIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, caption, password, locationsIds, clientAppsIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessIdentifierUpdateRequest {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    locationsIds: ").append(toIndentedString(locationsIds)).append("\n");
    sb.append("    clientAppsIds: ").append(toIndentedString(clientAppsIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

