/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ChannelGroupRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-03T19:40:18.502Z")
public class ChannelGroupRequest {
  @SerializedName("caption")
  private String caption = null;

  @SerializedName("altIcon")
  private Integer altIcon = null;

  @SerializedName("hidden")
  private Boolean hidden = null;

  @SerializedName("locationId")
  private Integer locationId = null;

  @SerializedName("channelIds")
  private List<Integer> channelIds = new ArrayList<Integer>();

  public ChannelGroupRequest caption(String caption) {
    this.caption = caption;
    return this;
  }

   /**
   * Get caption
   * @return caption
  **/
  @ApiModelProperty(value = "")
  public String getCaption() {
    return caption;
  }

  public void setCaption(String caption) {
    this.caption = caption;
  }

  public ChannelGroupRequest altIcon(Integer altIcon) {
    this.altIcon = altIcon;
    return this;
  }

   /**
   * Get altIcon
   * @return altIcon
  **/
  @ApiModelProperty(value = "")
  public Integer getAltIcon() {
    return altIcon;
  }

  public void setAltIcon(Integer altIcon) {
    this.altIcon = altIcon;
  }

  public ChannelGroupRequest hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * Get hidden
   * @return hidden
  **/
  @ApiModelProperty(value = "")
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public ChannelGroupRequest locationId(Integer locationId) {
    this.locationId = locationId;
    return this;
  }

   /**
   * Get locationId
   * @return locationId
  **/
  @ApiModelProperty(value = "")
  public Integer getLocationId() {
    return locationId;
  }

  public void setLocationId(Integer locationId) {
    this.locationId = locationId;
  }

  public ChannelGroupRequest channelIds(List<Integer> channelIds) {
    this.channelIds = channelIds;
    return this;
  }

  public ChannelGroupRequest addChannelIdsItem(Integer channelIdsItem) {
    this.channelIds.add(channelIdsItem);
    return this;
  }

   /**
   * Get channelIds
   * @return channelIds
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Integer> getChannelIds() {
    return channelIds;
  }

  public void setChannelIds(List<Integer> channelIds) {
    this.channelIds = channelIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelGroupRequest channelGroupRequest = (ChannelGroupRequest) o;
    return Objects.equals(this.caption, channelGroupRequest.caption) &&
        Objects.equals(this.altIcon, channelGroupRequest.altIcon) &&
        Objects.equals(this.hidden, channelGroupRequest.hidden) &&
        Objects.equals(this.locationId, channelGroupRequest.locationId) &&
        Objects.equals(this.channelIds, channelGroupRequest.channelIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caption, altIcon, hidden, locationId, channelIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelGroupRequest {\n");
    
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    altIcon: ").append(toIndentedString(altIcon)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    channelIds: ").append(toIndentedString(channelIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

