/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ChannelFunctionAction;
import io.swagger.client.model.ChannelFunctionEnumNames;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ChannelFunction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-03T19:40:18.502Z")
public class ChannelFunction {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private ChannelFunctionEnumNames name = null;

  @SerializedName("caption")
  private String caption = null;

  @SerializedName("maxAlternativeIconIndex")
  private Integer maxAlternativeIconIndex = null;

  @SerializedName("possibleActions")
  private List<ChannelFunctionAction> possibleActions = null;

  public ChannelFunction id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "60", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ChannelFunction name(ChannelFunctionEnumNames name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public ChannelFunctionEnumNames getName() {
    return name;
  }

  public void setName(ChannelFunctionEnumNames name) {
    this.name = name;
  }

  public ChannelFunction caption(String caption) {
    this.caption = caption;
    return this;
  }

   /**
   * Get caption
   * @return caption
  **/
  @ApiModelProperty(example = "Gate opening sensor", value = "")
  public String getCaption() {
    return caption;
  }

  public void setCaption(String caption) {
    this.caption = caption;
  }

  public ChannelFunction maxAlternativeIconIndex(Integer maxAlternativeIconIndex) {
    this.maxAlternativeIconIndex = maxAlternativeIconIndex;
    return this;
  }

   /**
   * Get maxAlternativeIconIndex
   * @return maxAlternativeIconIndex
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxAlternativeIconIndex() {
    return maxAlternativeIconIndex;
  }

  public void setMaxAlternativeIconIndex(Integer maxAlternativeIconIndex) {
    this.maxAlternativeIconIndex = maxAlternativeIconIndex;
  }

  public ChannelFunction possibleActions(List<ChannelFunctionAction> possibleActions) {
    this.possibleActions = possibleActions;
    return this;
  }

  public ChannelFunction addPossibleActionsItem(ChannelFunctionAction possibleActionsItem) {
    if (this.possibleActions == null) {
      this.possibleActions = new ArrayList<ChannelFunctionAction>();
    }
    this.possibleActions.add(possibleActionsItem);
    return this;
  }

   /**
   * What can you with with this channel?
   * @return possibleActions
  **/
  @ApiModelProperty(value = "What can you with with this channel?")
  public List<ChannelFunctionAction> getPossibleActions() {
    return possibleActions;
  }

  public void setPossibleActions(List<ChannelFunctionAction> possibleActions) {
    this.possibleActions = possibleActions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelFunction channelFunction = (ChannelFunction) o;
    return Objects.equals(this.id, channelFunction.id) &&
        Objects.equals(this.name, channelFunction.name) &&
        Objects.equals(this.caption, channelFunction.caption) &&
        Objects.equals(this.maxAlternativeIconIndex, channelFunction.maxAlternativeIconIndex) &&
        Objects.equals(this.possibleActions, channelFunction.possibleActions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, caption, maxAlternativeIconIndex, possibleActions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelFunction {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    maxAlternativeIconIndex: ").append(toIndentedString(maxAlternativeIconIndex)).append("\n");
    sb.append("    possibleActions: ").append(toIndentedString(possibleActions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

