/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AccessIdentifier;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ClientApp
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-03T19:40:18.502Z")
public class ClientApp {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("caption")
  private String caption = null;

  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("regIpv4")
  private Integer regIpv4 = null;

  @SerializedName("regDate")
  private OffsetDateTime regDate = null;

  @SerializedName("lastAccessIpv4")
  private Integer lastAccessIpv4 = null;

  @SerializedName("lastAccessDate")
  private OffsetDateTime lastAccessDate = null;

  @SerializedName("softwareVersion")
  private String softwareVersion = null;

  @SerializedName("protocolVersion")
  private Integer protocolVersion = null;

  @SerializedName("accessIdId")
  private Integer accessIdId = null;

  @SerializedName("connected")
  private Boolean connected = null;

  @SerializedName("accessId")
  private AccessIdentifier accessId = null;

  public ClientApp id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Client application identifier
   * @return id
  **/
  @ApiModelProperty(value = "Client application identifier")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ClientApp name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClientApp caption(String caption) {
    this.caption = caption;
    return this;
  }

   /**
   * Get caption
   * @return caption
  **/
  @ApiModelProperty(value = "")
  public String getCaption() {
    return caption;
  }

  public void setCaption(String caption) {
    this.caption = caption;
  }

  public ClientApp enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public ClientApp regIpv4(Integer regIpv4) {
    this.regIpv4 = regIpv4;
    return this;
  }

   /**
   * Get regIpv4
   * @return regIpv4
  **/
  @ApiModelProperty(value = "")
  public Integer getRegIpv4() {
    return regIpv4;
  }

  public void setRegIpv4(Integer regIpv4) {
    this.regIpv4 = regIpv4;
  }

  public ClientApp regDate(OffsetDateTime regDate) {
    this.regDate = regDate;
    return this;
  }

   /**
   * Get regDate
   * @return regDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getRegDate() {
    return regDate;
  }

  public void setRegDate(OffsetDateTime regDate) {
    this.regDate = regDate;
  }

  public ClientApp lastAccessIpv4(Integer lastAccessIpv4) {
    this.lastAccessIpv4 = lastAccessIpv4;
    return this;
  }

   /**
   * Get lastAccessIpv4
   * @return lastAccessIpv4
  **/
  @ApiModelProperty(value = "")
  public Integer getLastAccessIpv4() {
    return lastAccessIpv4;
  }

  public void setLastAccessIpv4(Integer lastAccessIpv4) {
    this.lastAccessIpv4 = lastAccessIpv4;
  }

  public ClientApp lastAccessDate(OffsetDateTime lastAccessDate) {
    this.lastAccessDate = lastAccessDate;
    return this;
  }

   /**
   * Get lastAccessDate
   * @return lastAccessDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastAccessDate() {
    return lastAccessDate;
  }

  public void setLastAccessDate(OffsetDateTime lastAccessDate) {
    this.lastAccessDate = lastAccessDate;
  }

  public ClientApp softwareVersion(String softwareVersion) {
    this.softwareVersion = softwareVersion;
    return this;
  }

   /**
   * Get softwareVersion
   * @return softwareVersion
  **/
  @ApiModelProperty(value = "")
  public String getSoftwareVersion() {
    return softwareVersion;
  }

  public void setSoftwareVersion(String softwareVersion) {
    this.softwareVersion = softwareVersion;
  }

  public ClientApp protocolVersion(Integer protocolVersion) {
    this.protocolVersion = protocolVersion;
    return this;
  }

   /**
   * Get protocolVersion
   * @return protocolVersion
  **/
  @ApiModelProperty(value = "")
  public Integer getProtocolVersion() {
    return protocolVersion;
  }

  public void setProtocolVersion(Integer protocolVersion) {
    this.protocolVersion = protocolVersion;
  }

  public ClientApp accessIdId(Integer accessIdId) {
    this.accessIdId = accessIdId;
    return this;
  }

   /**
   * Get accessIdId
   * @return accessIdId
  **/
  @ApiModelProperty(value = "")
  public Integer getAccessIdId() {
    return accessIdId;
  }

  public void setAccessIdId(Integer accessIdId) {
    this.accessIdId = accessIdId;
  }

  public ClientApp connected(Boolean connected) {
    this.connected = connected;
    return this;
  }

   /**
   * Get connected
   * @return connected
  **/
  @ApiModelProperty(value = "")
  public Boolean isConnected() {
    return connected;
  }

  public void setConnected(Boolean connected) {
    this.connected = connected;
  }

  public ClientApp accessId(AccessIdentifier accessId) {
    this.accessId = accessId;
    return this;
  }

   /**
   * Get accessId
   * @return accessId
  **/
  @ApiModelProperty(value = "")
  public AccessIdentifier getAccessId() {
    return accessId;
  }

  public void setAccessId(AccessIdentifier accessId) {
    this.accessId = accessId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientApp clientApp = (ClientApp) o;
    return Objects.equals(this.id, clientApp.id) &&
        Objects.equals(this.name, clientApp.name) &&
        Objects.equals(this.caption, clientApp.caption) &&
        Objects.equals(this.enabled, clientApp.enabled) &&
        Objects.equals(this.regIpv4, clientApp.regIpv4) &&
        Objects.equals(this.regDate, clientApp.regDate) &&
        Objects.equals(this.lastAccessIpv4, clientApp.lastAccessIpv4) &&
        Objects.equals(this.lastAccessDate, clientApp.lastAccessDate) &&
        Objects.equals(this.softwareVersion, clientApp.softwareVersion) &&
        Objects.equals(this.protocolVersion, clientApp.protocolVersion) &&
        Objects.equals(this.accessIdId, clientApp.accessIdId) &&
        Objects.equals(this.connected, clientApp.connected) &&
        Objects.equals(this.accessId, clientApp.accessId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, caption, enabled, regIpv4, regDate, lastAccessIpv4, lastAccessDate, softwareVersion, protocolVersion, accessIdId, connected, accessId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientApp {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    regIpv4: ").append(toIndentedString(regIpv4)).append("\n");
    sb.append("    regDate: ").append(toIndentedString(regDate)).append("\n");
    sb.append("    lastAccessIpv4: ").append(toIndentedString(lastAccessIpv4)).append("\n");
    sb.append("    lastAccessDate: ").append(toIndentedString(lastAccessDate)).append("\n");
    sb.append("    softwareVersion: ").append(toIndentedString(softwareVersion)).append("\n");
    sb.append("    protocolVersion: ").append(toIndentedString(protocolVersion)).append("\n");
    sb.append("    accessIdId: ").append(toIndentedString(accessIdId)).append("\n");
    sb.append("    connected: ").append(toIndentedString(connected)).append("\n");
    sb.append("    accessId: ").append(toIndentedString(accessId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

