/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ScheduleFuture;
import io.swagger.client.model.SchedulePast;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ScheduleClosestExecutions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-03T19:40:18.502Z")
public class ScheduleClosestExecutions {
  @SerializedName("past")
  private List<SchedulePast> past = null;

  @SerializedName("future")
  private List<ScheduleFuture> future = null;

  public ScheduleClosestExecutions past(List<SchedulePast> past) {
    this.past = past;
    return this;
  }

  public ScheduleClosestExecutions addPastItem(SchedulePast pastItem) {
    if (this.past == null) {
      this.past = new ArrayList<SchedulePast>();
    }
    this.past.add(pastItem);
    return this;
  }

   /**
   * Get past
   * @return past
  **/
  @ApiModelProperty(value = "")
  public List<SchedulePast> getPast() {
    return past;
  }

  public void setPast(List<SchedulePast> past) {
    this.past = past;
  }

  public ScheduleClosestExecutions future(List<ScheduleFuture> future) {
    this.future = future;
    return this;
  }

  public ScheduleClosestExecutions addFutureItem(ScheduleFuture futureItem) {
    if (this.future == null) {
      this.future = new ArrayList<ScheduleFuture>();
    }
    this.future.add(futureItem);
    return this;
  }

   /**
   * Get future
   * @return future
  **/
  @ApiModelProperty(value = "")
  public List<ScheduleFuture> getFuture() {
    return future;
  }

  public void setFuture(List<ScheduleFuture> future) {
    this.future = future;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleClosestExecutions scheduleClosestExecutions = (ScheduleClosestExecutions) o;
    return Objects.equals(this.past, scheduleClosestExecutions.past) &&
        Objects.equals(this.future, scheduleClosestExecutions.future);
  }

  @Override
  public int hashCode() {
    return Objects.hash(past, future);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleClosestExecutions {\n");
    
    sb.append("    past: ").append(toIndentedString(past)).append("\n");
    sb.append("    future: ").append(toIndentedString(future)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

