/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SchedulesEnableRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-03T19:40:18.502Z")
public class SchedulesEnableRequest {
  @SerializedName("enable")
  private List<Integer> enable = null;

  public SchedulesEnableRequest enable(List<Integer> enable) {
    this.enable = enable;
    return this;
  }

  public SchedulesEnableRequest addEnableItem(Integer enableItem) {
    if (this.enable == null) {
      this.enable = new ArrayList<Integer>();
    }
    this.enable.add(enableItem);
    return this;
  }

   /**
   * Array of schedule identifiers to enable
   * @return enable
  **/
  @ApiModelProperty(value = "Array of schedule identifiers to enable")
  public List<Integer> getEnable() {
    return enable;
  }

  public void setEnable(List<Integer> enable) {
    this.enable = enable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchedulesEnableRequest schedulesEnableRequest = (SchedulesEnableRequest) o;
    return Objects.equals(this.enable, schedulesEnableRequest.enable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchedulesEnableRequest {\n");
    
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

