/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ScheduleFuture
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-03T19:40:18.502Z")
public class ScheduleFuture {
  @SerializedName("plannedTimestamp")
  private OffsetDateTime plannedTimestamp = null;

  public ScheduleFuture plannedTimestamp(OffsetDateTime plannedTimestamp) {
    this.plannedTimestamp = plannedTimestamp;
    return this;
  }

   /**
   * Get plannedTimestamp
   * @return plannedTimestamp
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getPlannedTimestamp() {
    return plannedTimestamp;
  }

  public void setPlannedTimestamp(OffsetDateTime plannedTimestamp) {
    this.plannedTimestamp = plannedTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleFuture scheduleFuture = (ScheduleFuture) o;
    return Objects.equals(this.plannedTimestamp, scheduleFuture.plannedTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plannedTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleFuture {\n");
    
    sb.append("    plannedTimestamp: ").append(toIndentedString(plannedTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

