/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pl.grzeslowski.jsupla.api.api;

import pl.grzeslowski.jsupla.api.ApiException;
import pl.grzeslowski.jsupla.api.model.ClientApp;
import pl.grzeslowski.jsupla.api.model.ClientAppUpdateRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for ClientAppsApi
 */
@Ignore
public class ClientAppsApiTest {

    private final ClientAppsApi api = new ClientAppsApi();

    
    /**
     * Delete Client App
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteClientAppTest() throws ApiException {
        Integer id = null;
        api.deleteClientApp(id);

        // TODO: test validations
    }
    
    /**
     * Get client apps
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClientAppsTest() throws ApiException {
        List<String> include = null;
        List<ClientApp> response = api.getClientApps(include);

        // TODO: test validations
    }
    
    /**
     * Update client app
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateClientAppTest() throws ApiException {
        Integer id = null;
        ClientAppUpdateRequest body = null;
        ClientApp response = api.updateClientApp(id, body);

        // TODO: test validations
    }
    
}
