/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pl.grzeslowski.jsupla.api.api;

import pl.grzeslowski.jsupla.api.ApiException;
import pl.grzeslowski.jsupla.api.model.ERRORUNKNOWN;
import pl.grzeslowski.jsupla.api.model.UserUpdateRequest;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Get current user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrentUserTest() throws ApiException {
        ERRORUNKNOWN response = api.getCurrentUser();

        // TODO: test validations
    }
    
    /**
     * Update current user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCurrentUserTest() throws ApiException {
        UserUpdateRequest body = null;
        api.updateCurrentUser(body);

        // TODO: test validations
    }
    
}
