/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ChannelExecuteActionRequest;
import io.swagger.client.model.ChannelGroup;
import io.swagger.client.model.ChannelGroupRequest;
import io.swagger.client.model.ERRORUNKNOWN;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChannelGroupsApi
 */
@Ignore
public class ChannelGroupsApiTest {

    private final ChannelGroupsApi api = new ChannelGroupsApi();

    
    /**
     * Create a new channel group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createChannelGroupTest() throws ApiException {
        ChannelGroupRequest body = null;
        ChannelGroup response = api.createChannelGroup(body);

        // TODO: test validations
    }
    
    /**
     * Delete Channel Group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteChannelGroupTest() throws ApiException {
        Integer id = null;
        api.deleteChannelGroup(id);

        // TODO: test validations
    }
    
    /**
     * Execute action on the channel group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void executeChannelGroupActionTest() throws ApiException {
        Integer id = null;
        ChannelExecuteActionRequest body = null;
        api.executeChannelGroupAction(id, body);

        // TODO: test validations
    }
    
    /**
     * Get channel group by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChannelGroupTest() throws ApiException {
        Integer id = null;
        List<String> include = null;
        ChannelGroup response = api.getChannelGroup(id, include);

        // TODO: test validations
    }
    
    /**
     * Get channels list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChannelGroupsTest() throws ApiException {
        List<String> include = null;
        List<ChannelGroup> response = api.getChannelGroups(include);

        // TODO: test validations
    }
    
    /**
     * Update channel group
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateChannelGroupTest() throws ApiException {
        Integer id = null;
        ChannelGroupRequest body = null;
        ChannelGroup response = api.updateChannelGroup(id, body);

        // TODO: test validations
    }
    
}
