/*
 * SUPLA Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Channel;
import io.swagger.client.model.Device;
import io.swagger.client.model.IODeviceUpdateRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IoDevicesApi
 */
@Ignore
public class IoDevicesApiTest {

    private final IoDevicesApi api = new IoDevicesApi();

    
    /**
     * Delete IO Device
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteIoDeviceTest() throws ApiException {
        Integer id = null;
        api.deleteIoDevice(id);

        // TODO: test validations
    }
    
    /**
     * Get IO Device
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIoDeviceTest() throws ApiException {
        Integer id = null;
        List<String> include = null;
        Device response = api.getIoDevice(id, include);

        // TODO: test validations
    }
    
    /**
     * Get Channels that belong to IO Deice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIoDeviceChannelsTest() throws ApiException {
        Integer id = null;
        List<String> include = null;
        Channel response = api.getIoDeviceChannels(id, include);

        // TODO: test validations
    }
    
    /**
     * Get IO Devices
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIoDevicesTest() throws ApiException {
        List<String> include = null;
        List<Device> response = api.getIoDevices(include);

        // TODO: test validations
    }
    
    /**
     * Update IO Device
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateIoDeviceTest() throws ApiException {
        Integer id = null;
        IODeviceUpdateRequest body = null;
        Device response = api.updateIoDevice(id, body);

        // TODO: test validations
    }
    
}
